import Head from 'next/head';
import styled, { createGlobalStyle } from 'styled-components';
import { createContext, useLayoutEffect, useState } from 'react';
import {
    outsidePadding,
    insidePadding,
    headerHeight,
    footerHeight,
    menuSpeed,
} from '../styles/GlobalVariables';
import Footer from './Footer';
import Header from './Header';
import MainContainer from './MainContainer';
import { useRouter } from 'next/router';

export const AppContext = createContext(null);

const GlobalStyle = createGlobalStyle`
    body {
        background-color: ${(props) =>
            props.page === 'home'
                ? '#C5283D'
                : props.page === 'work'
                ? '#28c5b0'
                : props.page === 'about'
                ? '#8BC528'
                : props.page === 'contact'
                ? '#6228C5'
                : null};
        padding: 0;
        margin: 0;
        color: #fff;
        font-family: 'Maven Pro';
        transition: background-color ${menuSpeed}ms ease-in-out;
    }
    * {
        box-sizing: border-box;
    }
`;

const PageWrapper = styled.div`
    width: 100%;
    height: 100vh;
    padding: ${outsidePadding}px;
    display: flex;
    flex-direction: column;
    position: relative;
`;

const PageBorder = styled.div`
    border: 6px solid #fff;
    height: 100vh;
    position: relative;
    overflow: hidden;
`;

const StyledHeader = styled(Header)`
    text-align: center;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    z-index: 2;
    padding: ${insidePadding}px;
    height: ${headerHeight}px;
    font-family: 'Slabo 27px';
    font-size: 32px;
    letter-spacing: -0.2px;
`;

const StyledMainContainer = styled(MainContainer)`
    overflow: auto;
    height: 100%;
    padding: ${insidePadding}px;
    padding-top: ${headerHeight}px;
    padding-bottom: ${footerHeight}px;
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 0;
`;

const StyledFooter = styled(Footer)`
    text-align: center;
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 1;
    padding: ${insidePadding}px;
    height: ${footerHeight}px;
    font-size: 12px;
    color: #fff;
`;

const Layout = ({ children }) => {
    const [openMenu, setOpenMenu] = useState(false);
    const [page, setPage] = useState('home');

    const router = useRouter();

    useLayoutEffect(() => {
        if (location.pathname === '/work') {
            setPage('work');
        } else if (location.pathname === '/about') {
            setPage('about');
        } else if (location.pathname === '/contact') {
            setPage('contact');
        } else {
            setPage('home');
        }
    }, [router.asPath]);

    return (
        <>
            <AppContext.Provider value={{ openMenu, setOpenMenu }}>
                <GlobalStyle page={page} />
                <PageWrapper>
                    <PageBorder>
                        <Head>
                            <title>Teva Barzilay</title>
                            <meta
                                name='description'
                                content='Generated by create next app'
                            />
                            <meta
                                name='viewport'
                                content='width=device-width, initial-scale=1'
                            />
                        </Head>
                        <StyledHeader />
                        <StyledMainContainer>{children}</StyledMainContainer>
                        <StyledFooter />
                    </PageBorder>
                </PageWrapper>
            </AppContext.Provider>
        </>
    );
};

export default Layout;
